name: Flutter HaiGang Build

on:
  workflow_dispatch:
    inputs:
      is_trial_version:
        description: '是否编译试用版本'
        type: boolean
        default: true
  push:
    branches:
      - 1.4.5-haigang
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"


jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build-windows.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "haigang"
      is-trial-version: ${{ inputs.is_trial_version == '' && true || inputs.is_trial_version }}
