name: Flutter HaiGang Build

on:
  workflow_dispatch:
    inputs:
      is-trial-version:
        description: '是否编译试用版本'
        type: boolean
        default: true
  push:
    branches:
      - 1.4.5-haigang
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"


jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build-windows.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
      is-trial-version: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.is-trial-version == 'true' }}